# $ Hadamard \ Matrices:$
### The following program represents a function that takes in a natural number $k \in \mathbb{N}$ and computes the Matrix of order $2^k$
### note that hadamard matrices are the matrices made as follows:

\begin{gather*}
H_0 = (1)\\
\\
H_1 = \begin{pmatrix}
        H_0 & H_0\\
        H_0 & -H_0
    \end{pmatrix} = 
     \begin{pmatrix}
        1 & 1\\
        1 & -1
    \end{pmatrix}\\ 
\\
H_2 = \begin{pmatrix}
        H_1 & H_1\\
        H_1 & -H_1
    \end{pmatrix} = 
     \begin{pmatrix}
        1 & 1 & 1 & 1\\
        1 & -1 & 1 & -1 \\
        1 & 1 & -1 & -1 \\
        1 & -1 & -1 & 1
    \end{pmatrix} =
\\
.\\
.\\
.\\
\\
H_n = \begin{pmatrix}
        H_{n-1} & H_{n-1}\\
        H_{n-1} & -H_{n-1}
    \end{pmatrix}
\end{gather*}


#### *- Hadamard Matrices Generator:

In [1]:
import numpy as np

def Hadamard_Matrix(n):
    if n==0:
        return 1
    else:
        return np.vstack((np.hstack((Hadamard_Matrix(n-1), Hadamard_Matrix(n-1))),np.hstack((Hadamard_Matrix(n-1), -Hadamard_Matrix(n-1)))))

# Test Cell

In [2]:
print(Hadamard_Matrix(4))

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]
