# $Toeplitz \ Matrix$
## Exercise 7: 
### The following program consists of a function that takes in an integer as input then makes a matrix where the first line is the vector

\begin{gather*}
    x = (1, 2, 3, ... ,n) 
\end{gather*}

### which then shifts its components and makes the matrix with the n times shifts of that vector that is :

\begin{gather*}
    L1 = x \\
    L2 = (n, 1, 2, ..., n-1)\\
    L3 = (n-1, n, 1, ..., n-2)\\
    .\\
    .\\
    .\\
    Ln = (2, 3, 4, ..., n-1, n, 1)\\
\end{gather*}

### Hense giving us the following Matrix:

\begin{gather*}
    M = \begin{pmatrix}
        1 & 2 & 3 & ... & n \\
        n & 1 & 2 & ... & n-1 \\
        n-1 & n & 1 & ... & n-2 \\
        . & . & . & . & . \\
        . & . & . & . & . \\
        . & . & . & . & . \\
        2 & 3 & 4 & ... & 1
        \end{pmatrix}
\end{gather*}

#### *- Toeplitz matrices generating function:

In [13]:
import numpy as np

def Toeplitz_Matrix(n):
    x = np.array(list(range(1, n + 1))) 
    matrix = [x]

    for step in range(1, n):
        vector = []
        vector = np.hstack((np.array(list(range(x[-step], n + 1))), np.array(x[:-step])))
        matrix = np.vstack((matrix, vector))
        
    return matrix

# Test Cell

In [17]:
print(Toeplitz_Matrix(20))

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [19 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [18 19 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [17 18 19 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [16 17 18 19 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [15 16 17 18 19 20  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9 10 11 12]
 [12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9 10 11]
 [11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9 10]
 [10 11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9]
 [ 9 10 11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8]
 [ 8  9 10 11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7]
 [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6]
 [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20  1  2  3